"""Single source of truth for all constants used across the pipeline."""
from pathlib import Path
from typing import Literal

# ── Allowed positions / teams / players ───────────────────

ALLOWED_POSITIONS = Literal[
  'Center',
  'Center-Forward',
  'Forward',
  'Forward-Guard',
  'Guard',
  'Guard-Forward',
  'Forward-Center'
]

ALLOWED_TEAMS = Literal[
  'ATL', 'BOS', 'BKN', 'CHA', 'CHI', 'CLE', 'DAL', 'DEN', 'DET',
  'GSW', 'HOU', 'IND', 'LAC', 'LAL', 'MEM', 'MIA', 'MIL', 'MIN',
  'NOP', 'NYK', 'OKC', 'ORL', 'PHI', 'PHX', 'POR', 'SAC', 'SAS',
  'TOR', 'UTA', 'WAS'
]

ALLOWED_PLAYERS_LIST = [
  'Aaron Gordon',
  'Ace Bailey',
  'Alex Caruso',
  'Alex Sarr',
  'Alperen Sengun',
  'Amen Thompson',
  'Andrew Nembhard',
  'Anthony Davis',
  'Anthony Edwards',
  'Anfernee Simons',
  'Ausar Thompson',
  'Austin Reaves',
  'Bam Adebayo',
  'Bennedict Mathurin',
  'Brandin Podziemski',
  'Brandon Ingram',
  'Brandon Miller',
  'CJ McCollum',
  'Cade Cunningham',
  'Cam Thomas',
  'Chet Holmgren',
  'Coby White',
  'Collin Sexton',
  'Cooper Flagg',
  "D'Angelo Russell",
  'Darius Garland',
  "De'Aaron Fox",
  'DeMar DeRozan',
  'Deandre Ayton',
  'Dejounte Murray',
  'Deni Avdija',
  'Derrick White',
  'Desmond Bane',
  'Devin Booker',
  'Dillon Brooks',
  'Domantas Sabonis',
  'Donovan Mitchell',
  'Donte DiVincenzo',
  'Draymond Green',
  'Dyson Daniels',
  'Evan Mobley',
  'Franz Wagner',
  'Fred VanVleet',
  'Giannis Antetokounmpo',
  'Immanuel Quickley',
  'Isaiah Hartenstein',
  'Ivica Zubac',
  'Ja Morant',
  'Jaden McDaniels',
  'Jaden Ivey',
  'Jaime Jaquez Jr.',
  'Jalen Brunson',
  'Jalen Duren',
  'Jalen Green',
  'Jalen Johnson',
  'Jalen Suggs',
  'Jalen Williams',
  'Jamal Murray',
  'James Harden',
  'Jaren Jackson Jr.',
  'Jarrett Allen',
  'Jaylen Brown',
  'Jaylen Wells',
  'Jayson Tatum',
  'Jerami Grant',
  'Jimmy Butler III',
  'Joel Embiid',
  'Jonathan Kuminga',
  'Jordan Poole',
  'Josh Giddey',
  'Josh Hart',
  'Jrue Holiday',
  'Julius Randle',
  'Jusuf Nurkić',
  'Karl-Anthony Towns',
  'Kawhi Leonard',
  'Keegan Murray',
  'Kelly Oubre Jr.',
  'Kentavious Caldwell-Pope',
  'Kevin Durant',
  'Kevin Love',
  'Kevin Porter Jr.',
  'Keyonte George',
  'Khris Middleton',
  'Klay Thompson',
  'Kon Knueppel',
  'Kristaps Porziņģis',
  'Kyle Kuzma',
  'Kyrie Irving',
  'Kyshawn George',
  'LaMelo Ball',
  'Lauri Markkanen',
  'LeBron James',
  'Lonzo Ball',
  'Luka Dončić',
  'Marcus Smart',
  'Michael Porter Jr.',
  'Mikal Bridges',
  'Miles Bridges',
  'Myles Turner',
  'Naz Reid',
  'Nikola Jokić',
  'Nikola Vučević',
  'Norman Powell',
  'OG Anunoby',
  'Onyeka Okongwu',
  'P.J. Washington',
  'Paolo Banchero',
  'Pascal Siakam',
  'Paul George',
  'Payton Pritchard',
  'Quentin Grimes',
  'RJ Barrett',
  'Reed Sheppard',
  'Rudy Gobert',
  'Russell Westbrook',
  'Scottie Barnes',
  'Scoot Henderson',
  'Shaedon Sharpe',
  'Shai Gilgeous-Alexander',
  'Stephen Curry',
  'Stephon Castle',
  'Steven Adams',
  'Tim Hardaway Jr.',
  'Tobias Harris',
  'Trae Young',
  'Trey Murphy III',
  'Tyler Herro',
  'Tyrese Haliburton',
  'Tyrese Maxey',
  'VJ Edgecombe',
  'Victor Wembanyama',
  'Zach LaVine',
  'Zion Williamson',
]

ALLOWED_PLAYERS = Literal[
  'Aaron Gordon',
  'Ace Bailey',
  'Alex Caruso',
  'Alex Sarr',
  'Alperen Sengun',
  'Amen Thompson',
  'Andrew Nembhard',
  'Anthony Davis',
  'Anthony Edwards',
  'Anfernee Simons',
  'Ausar Thompson',
  'Austin Reaves',
  'Bam Adebayo',
  'Bennedict Mathurin',
  'Brandin Podziemski',
  'Brandon Ingram',
  'Brandon Miller',
  'CJ McCollum',
  'Cade Cunningham',
  'Cam Thomas',
  'Chet Holmgren',
  'Coby White',
  'Collin Sexton',
  'Cooper Flagg',
  "D'Angelo Russell",
  'Darius Garland',
  "De'Aaron Fox",
  'DeMar DeRozan',
  'Deandre Ayton',
  'Dejounte Murray',
  'Deni Avdija',
  'Derrick White',
  'Desmond Bane',
  'Devin Booker',
  'Dillon Brooks',
  'Domantas Sabonis',
  'Donovan Mitchell',
  'Donte DiVincenzo',
  'Draymond Green',
  'Dyson Daniels',
  'Evan Mobley',
  'Franz Wagner',
  'Fred VanVleet',
  'Giannis Antetokounmpo',
  'Immanuel Quickley',
  'Isaiah Hartenstein',
  'Ivica Zubac',
  'Ja Morant',
  'Jaden McDaniels',
  'Jaden Ivey',
  'Jaime Jaquez Jr.',
  'Jalen Brunson',
  'Jalen Duren',
  'Jalen Green',
  'Jalen Johnson',
  'Jalen Suggs',
  'Jalen Williams',
  'Jamal Murray',
  'James Harden',
  'Jaren Jackson Jr.',
  'Jarrett Allen',
  'Jaylen Brown',
  'Jaylen Wells',
  'Jayson Tatum',
  'Jerami Grant',
  'Jimmy Butler III',
  'Joel Embiid',
  'Jonathan Kuminga',
  'Jordan Poole',
  'Josh Giddey',
  'Josh Hart',
  'Jrue Holiday',
  'Julius Randle',
  'Jusuf Nurkić',
  'Karl-Anthony Towns',
  'Kawhi Leonard',
  'Keegan Murray',
  'Kelly Oubre Jr.',
  'Kentavious Caldwell-Pope',
  'Kevin Durant',
  'Kevin Love',
  'Kevin Porter Jr.',
  'Keyonte George',
  'Khris Middleton',
  'Klay Thompson',
  'Kon Knueppel',
  'Kristaps Porziņģis',
  'Kyle Kuzma',
  'Kyrie Irving',
  'Kyshawn George',
  'LaMelo Ball',
  'Lauri Markkanen',
  'LeBron James',
  'Lonzo Ball',
  'Luka Dončić',
  'Marcus Smart',
  'Michael Porter Jr.',
  'Mikal Bridges',
  'Miles Bridges',
  'Myles Turner',
  'Naz Reid',
  'Nikola Jokić',
  'Nikola Vučević',
  'Norman Powell',
  'OG Anunoby',
  'Onyeka Okongwu',
  'P.J. Washington',
  'Paolo Banchero',
  'Pascal Siakam',
  'Paul George',
  'Payton Pritchard',
  'Quentin Grimes',
  'RJ Barrett',
  'Reed Sheppard',
  'Rudy Gobert',
  'Russell Westbrook',
  'Scottie Barnes',
  'Scoot Henderson',
  'Shaedon Sharpe',
  'Shai Gilgeous-Alexander',
  'Stephen Curry',
  'Stephon Castle',
  'Steven Adams',
  'Tim Hardaway Jr.',
  'Tobias Harris',
  'Trae Young',
  'Trey Murphy III',
  'Tyler Herro',
  'Tyrese Haliburton',
  'Tyrese Maxey',
  'VJ Edgecombe',
  'Victor Wembanyama',
  'Zach LaVine',
  'Zion Williamson',
]

# ── Seasons ────────────────────────────────────────────────
SEASONS = ["2024-25", "2025-26"]

# ── Model root (relative to this file) ────────────────────
MODEL_ROOT = Path(__file__).parent / "models"
CATEGORY_MAPPINGS_PATH = MODEL_ROOT / "category_mappings.json"

# ── Stat columns ───────────────────────────────────────────
STAT_COLS = [
  "PTS", "REB", "AST", "STL", "BLK",
  "PRA", "PA", "PR", "RA", "SB",
  "TOV", "FTA", "FTM", "FGA", "FGM", "3PM", "3PA"
]

TARGET_COLUMNS = [
  'PTS', 'REB', 'AST', 'STL', 'BLK',
  'PRA', 'PA', 'PR', 'RA', 'SB',
  'TOV', 'FGM', '3PM', 'FTM', 'FGA', '3PA', 'FTA'
]

ALL_TARGETS = [f"TARGET_{s}" for s in STAT_COLS]

CATEGORY_COLS = ["PLAYER_NAME", "TEAM", "POSITION", "MATCHUP"]

DROP_BASE_COLS = [
  "PLAYER_NAME", "PLAYER_ID", "TEAM", "MATCHUP", "POSITION",
  "SEASON_YEAR", "SEASON_ID", "GAME_DATE", "GAME_ID",
  "PTS", "REB", "AST", "STL", "BLK", "PRA", "PA", "PR", "RA", "SB",
  "TOV", "FTM", "FGM", "3PM", "FGA", "3PA", "FTA",
  "MIN", "PLUS_MINUS", "TS%", "USG", "OFF_RATING"
]

# ── Model families ─────────────────────────────────────────
CHAMPION_FAMILIES = {
  "FULL_ALL": {
    "folder": "CHAMPION_FULL_ALL",
    "feature_mode": "full",
    "calibration_set": "ALL",
    "features_file": "FEATURES_FULL_ALL.pkl",
  },
  "FULL_TIGHT": {
    "folder": "CHAMPION_FULL_TIGHT",
    "feature_mode": "full",
    "calibration_set": "TIGHT",
    "features_file": "FEATURES_FULL_TIGHT.pkl",
  },
  "REDUCED_ALL": {
    "folder": "CHAMPION_REDUCED_ALL",
    "feature_mode": "reduced",
    "calibration_set": "ALL",
    "features_file": "FEATURES_REDUCED_ALL.pkl",
  },
  "REDUCED_TIGHT": {
    "folder": "CHAMPION_REDUCED_TIGHT",
    "feature_mode": "reduced",
    "calibration_set": "TIGHT",
    "features_file": "FEATURES_REDUCED_TIGHT.pkl",
  },
}

FAMILY_ORDER = ["FULL_ALL", "FULL_TIGHT", "REDUCED_ALL", "REDUCED_TIGHT"]

# ── New ranking weights (0–100 composite) ──────────────────
BREAKEVEN_PROB = 0.54  # breakeven for standard -110 bet
RANK_WEIGHTS = {
  "model_confidence": 0.20,
  "market_edge": 0.50,
  "model_alpha": 0.20,
  "family_agreement": 0.05,
  "statistical_signals": 0.05,
}

# ── Logging ────────────────────────────────────────────────
LOG_FORMAT = "%(asctime)s  %(levelname)-8s  %(name)s  %(message)s"

# ── Odds API: stat → market mapping ───────────────────────
STAT_TO_MARKET = {
  "PTS":  "player_points",
  "REB":  "player_rebounds",
  "AST":  "player_assists",
  "3PM":  "player_threes",
  "BLK":  "player_blocks",
  "STL":  "player_steals",
  "SB":   "player_blocks_steals",
  "TOV":  "player_turnovers",
  "PRA":  "player_points_rebounds_assists",
  "PR":   "player_points_rebounds",
  "PA":   "player_points_assists",
  "RA":   "player_rebounds_assists",
  "FGM":  "player_field_goals",
  "FTM":  "player_frees_made",
  "FTA":  "player_frees_attempts",
  # FGA and 3PA don't have standard Odds API markets
}

# ── Platform stat maps ─────────────────────────────────────
UNDERDOG_STAT_MAP = {
  "Points": "PTS",
  "Rebounds": "REB",
  "Assists": "AST",
  "Steals": "STL",
  "Blocks": "BLK",
  "Pts + Rebs + Asts": "PRA",
  "Pts+Rebs+Asts": "PRA",
  "Pts+Reb+Ast": "PRA",
  "Points + Assists": "PA",
  "Points+Assists": "PA",
  "Assists+Points": "PA",
  "Assists + Points": "PA",
  "Points + Rebounds": "PR",
  "Points+Rebounds": "PR",
  "Rebounds + Points": "PR",
  "Rebounds+Points": "PR",
  "Rebounds + Assists": "RA",
  "Rebounds+Assists": "RA",
  "Assists + Rebounds": "RA",
  "Assists+Rebounds": "RA",
  "Blocks + Steals": "SB",
  "Blocks+Steals": "SB",
  "Steals + Blocks": "SB",
  "Steals+Blocks": "SB",
  "Turnovers": "TOV",
  "FG Made": "FGM",
  "3-Pointers Made": "3PM",
  "3PM": "3PM",
  "FT Made": "FTM",
  "FG Attempted": "FGA",
  "3s Attempted": "3PA",
  "3PT Attempted": "3PA",
  "FT Attempted": "FTA",
}

PRIZEPICKS_STAT_MAP = {
  "Points":         "PTS",
  "Rebounds":       "REB",
  "Assists":        "AST",
  "Steals":         "STL",
  "Blocked Shots":  "BLK",
  "PRA":            "PRA",
  "Pts+Asts":       "PA",
  "Pts+Rebs":       "PR",
  "Rebs+Asts":      "RA",
  "Blks+Stls":      "SB",
  "Turnovers":      "TOV",
  "FG Made":        "FGM",
  "3PTM":           "3PM",
  "FTM":            "FTM",
  "FG Attempted":   "FGA",
  "3PTA":           "3PA",
  "FTA":            "FTA",
}
