STAT_COLS = [
  'PTS', 'REB', 'AST', 'STL', 'BLK',
  'PRA', 'PA', 'PR', 'RA', 'SB',
  'TOV', 'FTA', 'FTM', 'FGA', 'FGM', '3PM', '3PA'
]

ADVANCED_COLS = STAT_COLS + ['PLUS_MINUS', 'TS%', 'USG', 'MIN']

MATCHUP_ALLOWED_METRICS_W_PACE_DEF = ['PTS', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'FTA', 'FTM', 'FGA', 'FGM', '3PM', '3PA', 'PACE', 'DEF_RATING']
MATCHUP_ALLOWED_METRICS = ['PTS', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'FTA', 'FTM', 'FGA', 'FGM', '3PM', '3PA']

columns_to_keep_first_filter = [
  'PLAYER_NAME',
  'PLAYER_ID',
  'GAME_ID',
  'POSITION',
  'HEIGHT',
  'WEIGHT',
  'SEASON_YEAR',
  'SEASON_ID',
  'GAME_DATE',
  'TEAM',
  'MATCHUP',
  'HOME',
  'POSTSEASON',
  'BACK_TO_BACK',
  'PLAYER_REST_DAYS',
  'GAME_DIFF',
  'OFF_RATING',
  'PER_GROUPED',
  'OFF_RATING_GROUPED',
  'PLUS_MINUS_GROUPED',
  'GP_AGAINST_TEAM',

  'FATIGUE_FACTOR',
  'PACE_IMPACT_POSS',
  'AST_VULN_RATIO',
  'REB_VULN_RATIO',
  'DEF_VS_VOL',
  
  *[f"{col}" for col in ADVANCED_COLS],

  *[f"CUM_AVG_{col}" for col in ADVANCED_COLS],
  *[f"L5_AVG_{col}" for col in ADVANCED_COLS],
  *[f"STD_CUM_AVG_{col}" for col in ADVANCED_COLS],
  *[f"STD_L5_AVG_{col}" for col in ADVANCED_COLS],

  *[f"LAST_MATCHUP_{col}" for col in ADVANCED_COLS],
  *[f"MATCHUP_L4_AVG_{col}" for col in ADVANCED_COLS],
  *[f"MATCHUP_L4_STD_{col}" for col in ADVANCED_COLS],

  *[f"OPP_ALLOWED_{metric}_L5_AVG" for metric in MATCHUP_ALLOWED_METRICS],
  *[f"OPP_ALLOWED_{metric}_CUM_AVG" for metric in MATCHUP_ALLOWED_METRICS],
  'OPP_PACE_L5_AVG',
  'OPP_PACE_CUM_AVG',
  'OPP_DEF_RATING_L5_AVG',
  'OPP_DEF_RATING_CUM_AVG',

  *[f"MATCHUP_OPP_ALLOWED_{metric}_L4" for metric in MATCHUP_ALLOWED_METRICS_W_PACE_DEF],
]

columns_to_keep_second_filter = [
  'PLAYER_NAME',
  'PLAYER_ID',
  'GAME_ID',
  'POSITION',
  'HEIGHT',
  'WEIGHT',
  'SEASON_YEAR',
  'SEASON_ID',
  'GAME_DATE',
  'TEAM',
  'MATCHUP',
  'HOME',
  'POSTSEASON',
  'BACK_TO_BACK',
  'PLAYER_REST_DAYS',
  'OFF_RATING',
  'PER_GROUPED',
  'OFF_RATING_GROUPED',
  'PLUS_MINUS_GROUPED',
  'GP_AGAINST_TEAM',
  'GAMES_L3_DAYS',
  'GAMES_L7_DAYS',

  'FATIGUE_FACTOR',
  'PACE_IMPACT_POSS',
  'AST_VULN_RATIO',
  'REB_VULN_RATIO',
  'DEF_VS_VOL',


  *[f"{col}" for col in ADVANCED_COLS],
  *[f"TARGET_{col}" for col in STAT_COLS],
  *[f"PL_{col}" for col in STAT_COLS],

  *[f"CUM_AVG_{col}" for col in ADVANCED_COLS],
  *[f"L5_AVG_{col}" for col in ADVANCED_COLS],
  *[f"STD_CUM_AVG_{col}" for col in ADVANCED_COLS],
  *[f"STD_L5_AVG_{col}" for col in ADVANCED_COLS],

  *[f"{col}_LINE_DIFF" for col in STAT_COLS],
  *[f"{col}_Z_LINE" for col in STAT_COLS],
  *[f"{col}_Z_RECENT" for col in STAT_COLS],
  *[f'{col}_Z_MATCHUP' for col in STAT_COLS],
  *[f"CUM_AVG_{col}_PER_MIN" for col in STAT_COLS], 
  *[f"L5_{col}_PER_MIN" for col in STAT_COLS],
  *[f"{col}_LINE_DIFF_X_MIN" for col in STAT_COLS],
  *[f"{col}_MOMENTUM_X_VOL" for col in STAT_COLS],
  *[f"{col}_ANCHOR" for col in STAT_COLS],

  *[f"{col}_MOMENTUM" for col in ADVANCED_COLS],

  *[f"LAST_MATCHUP_{col}" for col in ADVANCED_COLS],
  *[f"MATCHUP_L4_AVG_{col}" for col in ADVANCED_COLS],
  *[f"MATCHUP_L4_STD_{col}" for col in ADVANCED_COLS],

  *[f"OPP_ALLOWED_{metric}_L5_AVG" for metric in MATCHUP_ALLOWED_METRICS],
  *[f"OPP_ALLOWED_{metric}_CUM_AVG" for metric in MATCHUP_ALLOWED_METRICS],
  'OPP_PACE_L5_AVG',
  'OPP_PACE_CUM_AVG',
  'OPP_DEF_RATING_L5_AVG',
  'OPP_DEF_RATING_CUM_AVG',

  *[f"MATCHUP_OPP_ALLOWED_{metric}_L4" for metric in MATCHUP_ALLOWED_METRICS_W_PACE_DEF],

  *[f"{col}_DIST_FROM_ANCHOR" for col in STAT_COLS],
  *[f"OVER_PL_RATE_{col}_L10" for col in STAT_COLS],
  *[f"OVER_PL_RATE_{col}_L5" for col in STAT_COLS],
]

required_names = {
  'Aaron Gordon',
  'Ace Bailey',
  'Alex Caruso',
  'Alex Sarr',
  'Alperen Sengun',
  'Amen Thompson',
  'Andrew Nembhard',
  'Anthony Davis',
  'Anthony Edwards',
  'Anfernee Simons',
  'Ausar Thompson',
  'Austin Reaves',
  'Bam Adebayo',
  'Bennedict Mathurin',
  'Brandin Podziemski',
  'Brandon Ingram',
  'Brandon Miller',
  'CJ McCollum',
  'Cade Cunningham',
  'Cam Thomas',
  'Chet Holmgren',
  'Coby White',
  'Collin Sexton',
  'Cooper Flagg',
  "D'Angelo Russell",
  'Darius Garland',
  "De'Aaron Fox",
  'DeMar DeRozan',
  'Deandre Ayton',
  'Dejounte Murray',
  'Deni Avdija',
  'Derrick White',
  'Desmond Bane',
  'Devin Booker',
  'Dillon Brooks',
  'Domantas Sabonis',
  'Donovan Mitchell',
  'Donte DiVincenzo',
  'Draymond Green',
  'Dyson Daniels',
  'Evan Mobley',
  'Franz Wagner',
  'Fred VanVleet',
  'Giannis Antetokounmpo',
  'Immanuel Quickley',
  'Isaiah Hartenstein',
  'Ivica Zubac',
  'Ja Morant',
  'Jaden McDaniels',
  'Jaden Ivey',
  'Jaime Jaquez Jr.',
  'Jalen Brunson',
  'Jalen Duren',
  'Jalen Green',
  'Jalen Johnson',
  'Jalen Suggs',
  'Jalen Williams',
  'Jamal Murray',
  'James Harden',
  'Jaren Jackson Jr.',
  'Jarrett Allen',
  'Jaylen Brown',
  'Jaylen Wells',
  'Jayson Tatum',
  'Jerami Grant',
  'Jimmy Butler III',
  'Joel Embiid',
  'Jonathan Kuminga',
  'Jordan Poole',
  'Josh Giddey',
  'Josh Hart',
  'Jrue Holiday',
  'Julius Randle',
  'Jusuf Nurkić',
  'Karl-Anthony Towns',
  'Kawhi Leonard',
  'Keegan Murray',
  'Kelly Oubre Jr.',
  'Kentavious Caldwell-Pope',
  'Kevin Durant',
  'Kevin Love',
  'Kevin Porter Jr.',
  'Keyonte George',
  'Khris Middleton',
  'Klay Thompson',
  'Kon Knueppel',
  'Kristaps Porziņģis',
  'Kyle Kuzma',
  'Kyrie Irving',
  'Kyshawn George',
  'LaMelo Ball',
  'Lauri Markkanen',
  'LeBron James',
  'Lonzo Ball',
  'Luka Dončić',
  'Marcus Smart',
  'Michael Porter Jr.',
  'Mikal Bridges',
  'Miles Bridges',
  'Myles Turner',
  'Naz Reid',
  'Nikola Jokić',
  'Nikola Vučević',
  'Norman Powell',
  'OG Anunoby',
  'Onyeka Okongwu',
  'P.J. Washington',
  'Paolo Banchero',
  'Pascal Siakam',
  'Paul George',
  'Payton Pritchard',
  'Quentin Grimes',
  'RJ Barrett',
  'Reed Sheppard',
  'Rudy Gobert',
  'Russell Westbrook',
  'Scottie Barnes',
  'Scoot Henderson',
  'Shaedon Sharpe',
  'Shai Gilgeous-Alexander',
  'Stephen Curry',
  'Stephon Castle',
  'Steven Adams',
  'Tim Hardaway Jr.',
  'Tobias Harris',
  'Trae Young',
  'Trey Murphy III',
  'Tyler Herro',
  'Tyrese Haliburton',
  'Tyrese Maxey',
  'VJ Edgecombe',
  'Victor Wembanyama',
  'Zach LaVine',
  'Zion Williamson',
}