from typing import Literal

ALLOWED_POSITIONS = Literal[
  'Center',
  'Center-Forward',
  'Forward',
  'Forward-Guard',
  'Guard',
  'Guard-Forward',
  'Forward-Center'
]

ALLOWED_TEAMS = Literal[
  'ATL', 'BOS', 'BKN', 'CHA', 'CHI', 'CLE', 'DAL', 'DEN', 'DET',
  'GSW', 'HOU', 'IND', 'LAC', 'LAL', 'MEM', 'MIA', 'MIL', 'MIN',
  'NOP', 'NYK', 'OKC', 'ORL', 'PHI', 'PHX', 'POR', 'SAC', 'SAS',
  'TOR', 'UTA', 'WAS'
]

ALLOWED_PLAYERS_LIST = [
  'Aaron Gordon',
  'Ace Bailey',
  'Alex Caruso',
  'Alex Sarr',
  'Alperen Sengun',
  'Amen Thompson',
  'Andrew Nembhard',
  'Anthony Davis',
  'Anthony Edwards',
  'Ausar Thompson',
  'Austin Reaves',
  'Bam Adebayo',
  'Bennedict Mathurin',
  'Brandin Podziemski',
  'Brandon Ingram',
  'Brandon Miller',
  'CJ McCollum',
  'Cade Cunningham',
  'Cam Thomas',
  'Chet Holmgren',
  'Coby White',
  'Collin Sexton',
  'Cooper Flagg',
  "D'Angelo Russell",
  'Darius Garland',
  "De'Aaron Fox",
  'DeMar DeRozan',
  'Deandre Ayton',
  'Deni Avdija',
  'Derrick White',
  'Desmond Bane',
  'Devin Booker',
  'Dillon Brooks',
  'Domantas Sabonis',
  'Donovan Mitchell',
  'Donte DiVincenzo',
  'Draymond Green',
  'Dyson Daniels',
  'Evan Mobley',
  'Franz Wagner',
  'Giannis Antetokounmpo',
  'Immanuel Quickley',
  'Isaiah Hartenstein',
  'Ivica Zubac',
  'Ja Morant',
  'Jaden McDaniels',
  'Jaime Jaquez Jr.',
  'Jalen Brunson',
  'Jalen Duren',
  'Jalen Green',
  'Jalen Johnson',
  'Jalen Suggs',
  'Jalen Williams',
  'Jamal Murray',
  'James Harden',
  'Jaren Jackson Jr.',
  'Jarrett Allen',
  'Jaylen Brown',
  'Jaylen Wells',
  'Jayson Tatum',
  'Jerami Grant',
  'Jimmy Butler III',
  'Joel Embiid',
  'Jonathan Kuminga',
  'Jordan Poole',
  'Josh Giddey',
  'Josh Hart',
  'Jrue Holiday',
  'Julius Randle',
  'Jusuf Nurkić',
  'Karl-Anthony Towns',
  'Kawhi Leonard',
  'Keegan Murray',
  'Kelly Oubre Jr.',
  'Kentavious Caldwell-Pope',
  'Kevin Durant',
  'Kevin Love',
  'Kevin Porter Jr.',
  'Keyonte George',
  'Khris Middleton',
  'Klay Thompson',
  'Kon Knueppel',
  'Kristaps Porziņģis',
  'Kyle Kuzma',
  'Kyrie Irving',
  'Kyshawn George',
  'LaMelo Ball',
  'Lauri Markkanen',
  'LeBron James',
  'Lonzo Ball',
  'Luka Dončić',
  'Marcus Smart',
  'Michael Porter Jr.',
  'Mikal Bridges',
  'Miles Bridges',
  'Myles Turner',
  'Naz Reid',
  'Nikola Jokić',
  'Nikola Vučević',
  'Norman Powell',
  'OG Anunoby',
  'Onyeka Okongwu',
  'P.J. Washington',
  'Paolo Banchero',
  'Pascal Siakam',
  'Paul George',
  'Payton Pritchard',
  'Quentin Grimes',
  'RJ Barrett',
  'Reed Sheppard',
  'Rudy Gobert',
  'Russell Westbrook',
  'Scottie Barnes',
  'Shaedon Sharpe',
  'Shai Gilgeous-Alexander',
  'Stephen Curry',
  'Stephon Castle',
  'Steven Adams',
  'Tim Hardaway Jr.',
  'Tobias Harris',
  'Trae Young',
  'Trey Murphy III',
  'Tyler Herro',
  'Tyrese Haliburton',
  'Tyrese Maxey',
  'VJ Edgecombe',
  'Victor Wembanyama',
  'Zach LaVine',
  'Zion Williamson'
]


ALLOWED_PLAYERS = Literal[
  'Aaron Gordon',
  'Ace Bailey',
  'Alex Caruso',
  'Alex Sarr',
  'Alperen Sengun',
  'Amen Thompson',
  'Andrew Nembhard',
  'Anthony Davis',
  'Anthony Edwards',
  'Ausar Thompson',
  'Austin Reaves',
  'Bam Adebayo',
  'Bennedict Mathurin',
  'Brandin Podziemski',
  'Brandon Ingram',
  'Brandon Miller',
  'CJ McCollum',
  'Cade Cunningham',
  'Cam Thomas',
  'Chet Holmgren',
  'Coby White',
  'Collin Sexton',
  'Cooper Flagg',
  "D'Angelo Russell",
  'Darius Garland',
  "De'Aaron Fox",
  'DeMar DeRozan',
  'Deandre Ayton',
  'Deni Avdija',
  'Derrick White',
  'Desmond Bane',
  'Devin Booker',
  'Dillon Brooks',
  'Domantas Sabonis',
  'Donovan Mitchell',
  'Donte DiVincenzo',
  'Draymond Green',
  'Dyson Daniels',
  'Evan Mobley',
  'Franz Wagner',
  'Giannis Antetokounmpo',
  'Immanuel Quickley',
  'Isaiah Hartenstein',
  'Ivica Zubac',
  'Ja Morant',
  'Jaden McDaniels',
  'Jaime Jaquez Jr.',
  'Jalen Brunson',
  'Jalen Duren',
  'Jalen Green',
  'Jalen Johnson',
  'Jalen Suggs',
  'Jalen Williams',
  'Jamal Murray',
  'James Harden',
  'Jaren Jackson Jr.',
  'Jarrett Allen',
  'Jaylen Brown',
  'Jaylen Wells',
  'Jayson Tatum',
  'Jerami Grant',
  'Jimmy Butler III',
  'Joel Embiid',
  'Jonathan Kuminga',
  'Jordan Poole',
  'Josh Giddey',
  'Josh Hart',
  'Jrue Holiday',
  'Julius Randle',
  'Jusuf Nurkić',
  'Karl-Anthony Towns',
  'Kawhi Leonard',
  'Keegan Murray',
  'Kelly Oubre Jr.',
  'Kentavious Caldwell-Pope',
  'Kevin Durant',
  'Kevin Love',
  'Kevin Porter Jr.',
  'Keyonte George',
  'Khris Middleton',
  'Klay Thompson',
  'Kon Knueppel',
  'Kristaps Porziņģis',
  'Kyle Kuzma',
  'Kyrie Irving',
  'Kyshawn George',
  'LaMelo Ball',
  'Lauri Markkanen',
  'LeBron James',
  'Lonzo Ball',
  'Luka Dončić',
  'Marcus Smart',
  'Michael Porter Jr.',
  'Mikal Bridges',
  'Miles Bridges',
  'Myles Turner',
  'Naz Reid',
  'Nikola Jokić',
  'Nikola Vučević',
  'Norman Powell',
  'OG Anunoby',
  'Onyeka Okongwu',
  'P.J. Washington',
  'Paolo Banchero',
  'Pascal Siakam',
  'Paul George',
  'Payton Pritchard',
  'Quentin Grimes',
  'RJ Barrett',
  'Reed Sheppard',
  'Rudy Gobert',
  'Russell Westbrook',
  'Scottie Barnes',
  'Shaedon Sharpe',
  'Shai Gilgeous-Alexander',
  'Stephen Curry',
  'Stephon Castle',
  'Steven Adams',
  'Tim Hardaway Jr.',
  'Tobias Harris',
  'Trae Young',
  'Trey Murphy III',
  'Tyler Herro',
  'Tyrese Haliburton',
  'Tyrese Maxey',
  'VJ Edgecombe',
  'Victor Wembanyama',
  'Zach LaVine',
  'Zion Williamson'
]


TARGET_COLUMNS = [
  'PTS', 'REB', 'AST', 'STL', 'BLK',
  'PRA', 'PA', 'PR', 'RA', 'SB',
  'TOV', 'FGM', '3PM', 'FTM', 'FGA', '3PA', 'FTA'
]

FEATURES_TO_DUMMY = [
  'PLAYER_NAME',
  'POSITION',
  'TEAM',
  'MATCHUP',
]
