from pydantic import BaseModel, Field
from enum import Enum
from constants import ALLOWED_PLAYERS, ALLOWED_POSITIONS, ALLOWED_TEAMS

class Stat(str, Enum):
  PTS = "PTS"
  REB = "REB"
  AST = "AST"
  STL = "STL"
  BLK = "BLK"
  PRA = "PRA"
  PA = "PA" 
  PR = "PR"
  RA = "RA"
  SB = "SB"
  TOV = "TOV"
  FGM = "FGM"
  FGA = "FGA"
  FTM = "FTM"
  FTA = "FTA"
  PM3 = "3PM"
  PA3 = "3PA"

class TestModelPredictionInput(BaseModel):
  model_config = {
      "extra": "ignore"
  }
  
  PLAYER_NAME: ALLOWED_PLAYERS = Field(...)
  POSITION: ALLOWED_POSITIONS = Field(...)
  HEIGHT: int = Field(...)
  WEIGHT: int = Field(...)

  HOME: int = Field(..., ge=0, le=1)
  POSTSEASON: int = Field(..., ge=0, le=1)
  BACK_TO_BACK: int = Field(..., ge=0, le=1)
  GAMES_LAST3_DAYS: int = Field(...)
  GAMES_LAST7_DAYS: int = Field(...)
  OPP_DEF_EASY: float = Field(...)
  
  TEAM: ALLOWED_TEAMS = Field(...)
  MATCHUP: ALLOWED_TEAMS = Field(...)

  PER_GROUPED: float = Field(...)
  ORtg_GROUPED: float = Field(...)
  PLUS_MINUS_GROUPED: float = Field(...)

  PL_PTS: float = Field(0, description="Player's parlay for points")
  PL_REB: float = Field(0, description="Player's parlay for rebounds")
  PL_AST: float = Field(0, description="Player's parlay for assists")
  PL_STL: float = Field(0, description="Player's parlay for steals")
  PL_BLK: float = Field(0, description="Player's parlay for blocks")
  PL_PRA: float = Field(0, description="Player's parlay for points + rebounds + assists")
  PL_PA: float = Field(0, description="Player's parlay for points + assists")
  PL_PR: float = Field(0, description="Player's parlay for points + rebounds")
  PL_RA: float = Field(0, description="Player's parlay for rebounds + assists")
  PL_SB: float = Field(0, description="Player's parlay for steals + blocks")
  PL_TOV: float = Field(0, description="Player's parlay for turnovers")
  PL_FGM: float = Field(0, description="Player's parlay for field goals made")
  PL_3PM: float = Field(0, description="Player's parlay for 3-point shots made")
  PL_FTM: float = Field(0, description="Player's parlay for free throws made")
  PL_FGA: float = Field(0, description="Player's parlay for field goals attempted")
  PL_3PA: float = Field(0, description="Player's parlay for 3-point shots attempted")
  PL_FTA: float = Field(0, description="Player's parlay for free throws attempted")

  CUMULATIVE_AVG_MIN: float = Field(...)
  CUMULATIVE_AVG_PTS: float = Field(...)
  CUMULATIVE_AVG_REB: float = Field(...)
  CUMULATIVE_AVG_AST: float = Field(...)
  CUMULATIVE_AVG_STL: float = Field(...)
  CUMULATIVE_AVG_BLK: float = Field(...)
  CUMULATIVE_AVG_PRA: float = Field(...)
  CUMULATIVE_AVG_PA: float = Field(...)
  CUMULATIVE_AVG_PR: float = Field(...)
  CUMULATIVE_AVG_RA: float = Field(...)
  CUMULATIVE_AVG_SB: float = Field(...)
  CUMULATIVE_AVG_TOV: float = Field(...)
  CUMULATIVE_AVG_FTM: float = Field(...)
  CUMULATIVE_AVG_FGM: float = Field(...)
  CUMULATIVE_AVG_3PM: float = Field(...)
  CUMULATIVE_AVG_FGA: float = Field(...)
  CUMULATIVE_AVG_3PA: float = Field(...)
  CUMULATIVE_AVG_FTA: float = Field(...)
  CUMULATIVE_AVG_PLUS_MINUS: float = Field(...)
  CUMULATIVE_AVG_TS: float = Field(..., alias="CUMULATIVE_AVG_TS%")
  CUMULATIVE_AVG_USG: float = Field(...)

  LAST5_AVG_MIN: float = Field(...)
  LAST5_AVG_PTS: float = Field(...)
  LAST5_AVG_REB: float = Field(...)
  LAST5_AVG_AST: float = Field(...)
  LAST5_AVG_STL: float = Field(...)
  LAST5_AVG_BLK: float = Field(...)
  LAST5_AVG_PRA: float = Field(...)
  LAST5_AVG_PA: float = Field(...)
  LAST5_AVG_PR: float = Field(...)
  LAST5_AVG_RA: float = Field(...)
  LAST5_AVG_SB: float = Field(...)
  LAST5_AVG_TOV: float = Field(...)
  LAST5_AVG_FTM: float = Field(...)
  LAST5_AVG_FGM: float = Field(...)
  LAST5_AVG_3PM: float = Field(...)
  LAST5_AVG_FGA: float = Field(...)
  LAST5_AVG_3PA: float = Field(...)
  LAST5_AVG_FTA: float = Field(...)
  LAST5_AVG_PLUS_MINUS: float = Field(...)
  LAST5_AVG_TS: float = Field(..., alias="LAST5_AVG_TS%")
  LAST5_AVG_USG: float = Field(...)

  LAST_MATCHUP_MIN: float = Field(...)
  LAST_MATCHUP_PTS: float = Field(...)
  LAST_MATCHUP_REB: float = Field(...)
  LAST_MATCHUP_AST: float = Field(...)
  LAST_MATCHUP_STL: float = Field(...)
  LAST_MATCHUP_BLK: float = Field(...)
  LAST_MATCHUP_PRA: float = Field(...)
  LAST_MATCHUP_PA: float = Field(...)
  LAST_MATCHUP_PR: float = Field(...)
  LAST_MATCHUP_RA: float = Field(...)
  LAST_MATCHUP_SB: float = Field(...)
  LAST_MATCHUP_TOV: float = Field(...)
  LAST_MATCHUP_FTM: float = Field(...)
  LAST_MATCHUP_FGM: float = Field(...)
  LAST_MATCHUP_3PM: float = Field(...)
  LAST_MATCHUP_FGA: float = Field(...)
  LAST_MATCHUP_3PA: float = Field(...)
  LAST_MATCHUP_FTA: float = Field(...)
  LAST_MATCHUP_PLUS_MINUS: float = Field(...)
  LAST_MATCHUP_TS: float = Field(..., alias="LAST_MATCHUP_TS%")
  LAST_MATCHUP_USG: float = Field(...)

  LAST_MATCHUP_AVG_MIN: float = Field(...)
  LAST_MATCHUP_AVG_PTS: float = Field(...)
  LAST_MATCHUP_AVG_REB: float = Field(...)
  LAST_MATCHUP_AVG_AST: float = Field(...)
  LAST_MATCHUP_AVG_STL: float = Field(...)
  LAST_MATCHUP_AVG_BLK: float = Field(...)
  LAST_MATCHUP_AVG_PRA: float = Field(...)
  LAST_MATCHUP_AVG_PA: float = Field(...)
  LAST_MATCHUP_AVG_PR: float = Field(...)
  LAST_MATCHUP_AVG_RA: float = Field(...)
  LAST_MATCHUP_AVG_SB: float = Field(...)
  LAST_MATCHUP_AVG_TOV: float = Field(...)
  LAST_MATCHUP_AVG_FTM: float = Field(...)
  LAST_MATCHUP_AVG_FGM: float = Field(...)
  LAST_MATCHUP_AVG_3PM: float = Field(...)
  LAST_MATCHUP_AVG_FGA: float = Field(...)
  LAST_MATCHUP_AVG_3PA: float = Field(...)
  LAST_MATCHUP_AVG_FTA: float = Field(...)
  LAST_MATCHUP_AVG_PLUS_MINUS: float = Field(...)
  LAST_MATCHUP_AVG_TS: float = Field(..., alias="LAST_MATCHUP_AVG_TS%")
  LAST_MATCHUP_AVG_USG: float = Field(...)

  MATCHUP_MIN_DELTA: float = Field(...)
  MATCHUP_PTS_DELTA: float = Field(...)
  MATCHUP_REB_DELTA: float = Field(...)
  MATCHUP_AST_DELTA: float = Field(...)
  MATCHUP_STL_DELTA: float = Field(...)
  MATCHUP_BLK_DELTA: float = Field(...)
  MATCHUP_PRA_DELTA: float = Field(...)
  MATCHUP_PA_DELTA: float = Field(...)
  MATCHUP_PR_DELTA: float = Field(...)
  MATCHUP_RA_DELTA: float = Field(...)
  MATCHUP_SB_DELTA: float = Field(...)
  MATCHUP_TOV_DELTA: float = Field(...)
  MATCHUP_FTM_DELTA: float = Field(...)
  MATCHUP_FGM_DELTA: float = Field(...)
  MATCHUP_3PM_DELTA: float = Field(...)
  MATCHUP_FGA_DELTA: float = Field(...)
  MATCHUP_3PA_DELTA: float = Field(...)
  MATCHUP_FTA_DELTA: float = Field(...)
  MATCHUP_PLUS_MINUS_DELTA: float = Field(...)
  MATCHUP_TS_DELTA: float = Field(..., alias="MATCHUP_TS%_DELTA")
  MATCHUP_USG_DELTA: float = Field(...)

  MIN_MOMENTUM: float = Field(...)
  PTS_MOMENTUM: float = Field(...)
  REB_MOMENTUM: float = Field(...)
  AST_MOMENTUM: float = Field(...)
  STL_MOMENTUM: float = Field(...)
  BLK_MOMENTUM: float = Field(...)
  PRA_MOMENTUM: float = Field(...)
  PA_MOMENTUM: float = Field(...)
  PR_MOMENTUM: float = Field(...)
  RA_MOMENTUM: float = Field(...)
  SB_MOMENTUM: float = Field(...)
  TOV_MOMENTUM: float = Field(...)
  FTM_MOMENTUM: float = Field(...)
  FGM_MOMENTUM: float = Field(...)
  THREEPM_MOMENTUM: float = Field(..., alias="3PM_MOMENTUM")
  FGA_MOMENTUM: float = Field(...)
  THREEPA_MOMENTUM: float = Field(..., alias="3PA_MOMENTUM")
  FTA_MOMENTUM: float = Field(...)
  PLUS_MINUS_MOMENTUM: float = Field(...)
  TS_MOMENTUM: float = Field(..., alias="TS%_MOMENTUM")
  USG_MOMENTUM: float = Field(...)

  CUMULATIVE_STD_PTS: float = Field(...)
  CUMULATIVE_STD_REB: float = Field(...)
  CUMULATIVE_STD_AST: float = Field(...)
  CUMULATIVE_STD_STL: float = Field(...)
  CUMULATIVE_STD_BLK: float = Field(...)
  CUMULATIVE_STD_PRA: float = Field(...)
  CUMULATIVE_STD_PA: float = Field(...)
  CUMULATIVE_STD_PR: float = Field(...)
  CUMULATIVE_STD_RA: float = Field(...)
  CUMULATIVE_STD_SB: float = Field(...)
  CUMULATIVE_STD_TOV: float = Field(...)
  CUMULATIVE_STD_FTM: float = Field(...)
  CUMULATIVE_STD_FGM: float = Field(...)
  CUMULATIVE_STD_3PM: float = Field(...)
  CUMULATIVE_STD_FGA: float = Field(...)
  CUMULATIVE_STD_3PA: float = Field(...)
  CUMULATIVE_STD_FTA: float = Field(...)

  STD_LAST5_PTS: float = Field(...)
  STD_LAST5_REB: float = Field(...)
  STD_LAST5_AST: float = Field(...)
  STD_LAST5_STL: float = Field(...)
  STD_LAST5_BLK: float = Field(...)
  STD_LAST5_PRA: float = Field(...)
  STD_LAST5_PA: float = Field(...)
  STD_LAST5_PR: float = Field(...)
  STD_LAST5_RA: float = Field(...)
  STD_LAST5_SB: float = Field(...)
  STD_LAST5_TOV: float = Field(...)
  STD_LAST5_FTM: float = Field(...)
  STD_LAST5_FGM: float = Field(...)
  STD_LAST5_3PM: float = Field(...)
  STD_LAST5_FGA: float = Field(...)
  STD_LAST5_3PA: float = Field(...)
  STD_LAST5_FTA: float = Field(...)

  STD_SPIKE_RATIO_PTS: float = Field(...)
  STD_SPIKE_RATIO_REB: float = Field(...)
  STD_SPIKE_RATIO_AST: float = Field(...)
  STD_SPIKE_RATIO_STL: float = Field(...)
  STD_SPIKE_RATIO_BLK: float = Field(...)
  STD_SPIKE_RATIO_PRA: float = Field(...)
  STD_SPIKE_RATIO_PA: float = Field(...)
  STD_SPIKE_RATIO_PR: float = Field(...)
  STD_SPIKE_RATIO_RA: float = Field(...)
  STD_SPIKE_RATIO_SB: float = Field(...)
  STD_SPIKE_RATIO_TOV: float = Field(...)
  STD_SPIKE_RATIO_FTM: float = Field(...)
  STD_SPIKE_RATIO_FGM: float = Field(...)
  STD_SPIKE_RATIO_3PM: float = Field(...)
  STD_SPIKE_RATIO_FGA: float = Field(...)
  STD_SPIKE_RATIO_3PA: float = Field(...)
  STD_SPIKE_RATIO_FTA: float = Field(...)

  PTS_Z_LINE: float = Field(...)
  REB_Z_LINE: float = Field(...)
  AST_Z_LINE: float = Field(...)
  STL_Z_LINE: float = Field(...)
  BLK_Z_LINE: float = Field(...)
  PRA_Z_LINE: float = Field(...)
  PA_Z_LINE: float = Field(...)
  PR_Z_LINE: float = Field(...)
  RA_Z_LINE: float = Field(...)
  SB_Z_LINE: float = Field(...)
  TOV_Z_LINE: float = Field(...)
  FTM_Z_LINE: float = Field(...)
  FGM_Z_LINE: float = Field(...)
  THREEPM_Z_LINE: float = Field(..., alias="3PM_Z_LINE")
  FGA_Z_LINE: float = Field(...)
  THREEPA_Z_LINE: float = Field(..., alias="3PA_Z_LINE")
  FTA_Z_LINE: float = Field(...)

  PTS_Z_RECENT: float = Field(...)
  REB_Z_RECENT: float = Field(...)
  AST_Z_RECENT: float = Field(...)
  STL_Z_RECENT: float = Field(...)
  BLK_Z_RECENT: float = Field(...)
  PRA_Z_RECENT: float = Field(...)
  PA_Z_RECENT: float = Field(...)
  PR_Z_RECENT: float = Field(...)
  RA_Z_RECENT: float = Field(...)
  SB_Z_RECENT: float = Field(...)
  TOV_Z_RECENT: float = Field(...)
  FTM_Z_RECENT: float = Field(...)
  FGM_Z_RECENT: float = Field(...)
  THREEPM_Z_RECENT: float = Field(..., alias="3PM_Z_RECENT")
  FGA_Z_RECENT: float = Field(...)
  THREEPA_Z_RECENT: float = Field(..., alias="3PA_Z_RECENT")
  FTA_Z_RECENT: float = Field(...)

  LINE_EDGE_PTS: float = Field(...)
  LINE_EDGE_REB: float = Field(...)
  LINE_EDGE_AST: float = Field(...)
  LINE_EDGE_STL: float = Field(...)
  LINE_EDGE_BLK: float = Field(...)
  LINE_EDGE_PRA: float = Field(...)
  LINE_EDGE_PA: float = Field(...)
  LINE_EDGE_PR: float = Field(...)
  LINE_EDGE_RA: float = Field(...)
  LINE_EDGE_SB: float = Field(...)
  LINE_EDGE_TOV: float = Field(...)
  LINE_EDGE_FTM: float = Field(...)
  LINE_EDGE_FGM: float = Field(...)
  LINE_EDGE_3PM: float = Field(...)
  LINE_EDGE_FGA: float = Field(...)
  LINE_EDGE_3PA: float = Field(...)
  LINE_EDGE_FTA: float = Field(...)
  
  LINE_AMBIGUITY_PTS: float = Field(...)
  LINE_AMBIGUITY_REB: float = Field(...)
  LINE_AMBIGUITY_AST: float = Field(...)
  LINE_AMBIGUITY_STL: float = Field(...)
  LINE_AMBIGUITY_BLK: float = Field(...)
  LINE_AMBIGUITY_PRA: float = Field(...)
  LINE_AMBIGUITY_PA: float = Field(...)
  LINE_AMBIGUITY_PR: float = Field(...)
  LINE_AMBIGUITY_RA: float = Field(...)
  LINE_AMBIGUITY_SB: float = Field(...)
  LINE_AMBIGUITY_TOV: float = Field(...)
  LINE_AMBIGUITY_FTM: float = Field(...)
  LINE_AMBIGUITY_FGM: float = Field(...)
  LINE_AMBIGUITY_3PM: float = Field(...)
  LINE_AMBIGUITY_FGA: float = Field(...)
  LINE_AMBIGUITY_3PA: float = Field(...)
  LINE_AMBIGUITY_FTA: float = Field(...)

  CUM_AVG_PTS_PER_MIN: float = Field(...)
  CUM_AVG_REB_PER_MIN: float = Field(...)
  CUM_AVG_AST_PER_MIN: float = Field(...)
  CUM_AVG_STL_PER_MIN: float = Field(...)
  CUM_AVG_BLK_PER_MIN: float = Field(...)
  CUM_AVG_PRA_PER_MIN: float = Field(...)
  CUM_AVG_PA_PER_MIN: float = Field(...)
  CUM_AVG_PR_PER_MIN: float = Field(...)
  CUM_AVG_RA_PER_MIN: float = Field(...)
  CUM_AVG_SB_PER_MIN: float = Field(...)
  CUM_AVG_TOV_PER_MIN: float = Field(...)
  CUM_AVG_FTM_PER_MIN: float = Field(...)
  CUM_AVG_FGM_PER_MIN: float = Field(...)
  CUM_AVG_3PM_PER_MIN: float = Field(...)
  CUM_AVG_FGA_PER_MIN: float = Field(...)
  CUM_AVG_3PA_PER_MIN: float = Field(...)
  CUM_AVG_FTA_PER_MIN: float = Field(...)

  LAST5_PTS_PER_MIN: float = Field(...)
  LAST5_REB_PER_MIN: float = Field(...)
  LAST5_AST_PER_MIN: float = Field(...)
  LAST5_STL_PER_MIN: float = Field(...)
  LAST5_BLK_PER_MIN: float = Field(...)
  LAST5_PRA_PER_MIN: float = Field(...)
  LAST5_PA_PER_MIN: float = Field(...)
  LAST5_PR_PER_MIN: float = Field(...)
  LAST5_RA_PER_MIN: float = Field(...)
  LAST5_SB_PER_MIN: float = Field(...)
  LAST5_TOV_PER_MIN: float = Field(...)
  LAST5_FTM_PER_MIN: float = Field(...)
  LAST5_FGM_PER_MIN: float = Field(...)
  LAST5_3PM_PER_MIN: float = Field(...)
  LAST5_FGA_PER_MIN: float = Field(...)
  LAST5_3PA_PER_MIN: float = Field(...)
  LAST5_FTA_PER_MIN: float = Field(...)

  PTS_LINE_DIFF_X_MIN: float = Field(...)
  REB_LINE_DIFF_X_MIN: float = Field(...)
  AST_LINE_DIFF_X_MIN: float = Field(...)
  STL_LINE_DIFF_X_MIN: float = Field(...)
  BLK_LINE_DIFF_X_MIN: float = Field(...)
  PRA_LINE_DIFF_X_MIN: float = Field(...)
  PA_LINE_DIFF_X_MIN: float = Field(...)
  PR_LINE_DIFF_X_MIN: float = Field(...)
  RA_LINE_DIFF_X_MIN: float = Field(...)
  SB_LINE_DIFF_X_MIN: float = Field(...)
  TOV_LINE_DIFF_X_MIN: float = Field(...)
  FTM_LINE_DIFF_X_MIN: float = Field(...)
  FGM_LINE_DIFF_X_MIN: float = Field(...)
  THREEPM_LINE_DIFF_X_MIN: float = Field(..., alias="3PM_LINE_DIFF_X_MIN")
  FGA_LINE_DIFF_X_MIN: float = Field(...)
  THREEPA_LINE_DIFF_X_MIN: float = Field(..., alias="3PA_LINE_DIFF_X_MIN")
  FTA_LINE_DIFF_X_MIN: float = Field(...)

  PTS_MOMENTUM_X_VOL: float = Field(...)
  REB_MOMENTUM_X_VOL: float = Field(...)
  AST_MOMENTUM_X_VOL: float = Field(...)
  STL_MOMENTUM_X_VOL: float = Field(...)
  BLK_MOMENTUM_X_VOL: float = Field(...)
  PRA_MOMENTUM_X_VOL: float = Field(...)
  PA_MOMENTUM_X_VOL: float = Field(...)
  PR_MOMENTUM_X_VOL: float = Field(...)
  RA_MOMENTUM_X_VOL: float = Field(...)
  SB_MOMENTUM_X_VOL: float = Field(...)
  TOV_MOMENTUM_X_VOL: float = Field(...)
  FTM_MOMENTUM_X_VOL: float = Field(...)
  FGM_MOMENTUM_X_VOL: float = Field(...)
  THREEPM_MOMENTUM_X_VOL: float = Field(..., alias="3PM_MOMENTUM_X_VOL")
  FGA_MOMENTUM_X_VOL: float = Field(...)
  THREEPA_MOMENTUM_X_VOL: float = Field(..., alias="3PA_MOMENTUM_X_VOL")
  FTA_MOMENTUM_X_VOL: float = Field(...)

  MATCHUP_EASINESS_PTS: float = Field(...)
  MATCHUP_EASINESS_REB: float = Field(...)
  MATCHUP_EASINESS_AST: float = Field(...)
  MATCHUP_EASINESS_STL: float = Field(...)
  MATCHUP_EASINESS_BLK: float = Field(...)
  MATCHUP_EASINESS_PRA: float = Field(...)
  MATCHUP_EASINESS_PA: float = Field(...)
  MATCHUP_EASINESS_PR: float = Field(...)
  MATCHUP_EASINESS_RA: float = Field(...)
  MATCHUP_EASINESS_SB: float = Field(...)
  MATCHUP_EASINESS_TOV: float = Field(...)
  MATCHUP_EASINESS_FTM: float = Field(...)
  MATCHUP_EASINESS_FGM: float = Field(...)
  MATCHUP_EASINESS_3PM: float = Field(...)
  MATCHUP_EASINESS_FGA: float = Field(...)
  MATCHUP_EASINESS_3PA: float = Field(...)
  MATCHUP_EASINESS_FTA: float = Field(...)

  OVER_PL_RATE_PTS_LAST10: float = Field(...)
  OVER_PL_RATE_REB_LAST10: float = Field(...)
  OVER_PL_RATE_AST_LAST10: float = Field(...)
  OVER_PL_RATE_STL_LAST10: float = Field(...)
  OVER_PL_RATE_BLK_LAST10: float = Field(...)
  OVER_PL_RATE_PRA_LAST10: float = Field(...)
  OVER_PL_RATE_PA_LAST10: float = Field(...)
  OVER_PL_RATE_PR_LAST10: float = Field(...)
  OVER_PL_RATE_RA_LAST10: float = Field(...)
  OVER_PL_RATE_SB_LAST10: float = Field(...)
  OVER_PL_RATE_TOV_LAST10: float = Field(...)
  OVER_PL_RATE_FTM_LAST10: float = Field(...)
  OVER_PL_RATE_FGM_LAST10: float = Field(...)
  OVER_PL_RATE_3PM_LAST10: float = Field(...)
  OVER_PL_RATE_FGA_LAST10: float = Field(...)
  OVER_PL_RATE_3PA_LAST10: float = Field(...)
  OVER_PL_RATE_FTA_LAST10: float = Field(...)

  OVER_PL_RATE_PTS_LAST5: float = Field(...)
  OVER_PL_RATE_REB_LAST5: float = Field(...)
  OVER_PL_RATE_AST_LAST5: float = Field(...)
  OVER_PL_RATE_STL_LAST5: float = Field(...)
  OVER_PL_RATE_BLK_LAST5: float = Field(...)
  OVER_PL_RATE_PRA_LAST5: float = Field(...)
  OVER_PL_RATE_PA_LAST5: float = Field(...)
  OVER_PL_RATE_PR_LAST5: float = Field(...)
  OVER_PL_RATE_RA_LAST5: float = Field(...)
  OVER_PL_RATE_SB_LAST5: float = Field(...)
  OVER_PL_RATE_TOV_LAST5: float = Field(...)
  OVER_PL_RATE_FTM_LAST5: float = Field(...)
  OVER_PL_RATE_FGM_LAST5: float = Field(...)
  OVER_PL_RATE_3PM_LAST5: float = Field(...)
  OVER_PL_RATE_FGA_LAST5: float = Field(...)
  OVER_PL_RATE_3PA_LAST5: float = Field(...)
  OVER_PL_RATE_FTA_LAST5: float = Field(...)

